services:

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/shared-images:/app/frontend/shared-images
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - "VITE_API_URL=${VITE_API_URL}"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
      - ./service-account-key.json:/service-account-key.json:ro
      - ./backend/shared-images:/app/backend/shared-images
    ports:
      - "8080:8080"
    environment:
      - "GCP_PROJECT_ID=${GCP_PROJECT_ID}"
      - "GOOGLE_APPLICATION_CREDENTIALS=/service-account-key.json"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
