services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8080:8080"
    environment:
      - "GCP_PROJECT_ID=${GCP_PROJECT_ID}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
